# Generated by Django 2.1 on 2018-09-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cars')),
                ('name', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=50)),
                ('year', models.BigIntegerField(default=0)),
                ('available', models.CharField(max_length=50)),
            ],
        ),
    ]
